services:
  c2v:
    image: manjieqi/claude2vertex
    container_name: c2v
    # ports:
    #   - 5000:5000
    volumes:
      - ./.env:/app/.env
      - ./auth:/app/auth
      - ./model_mapping.json:/app/model_mapping.json
    command: python main.py
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
